load("//build_scripts/bazel:java_rules.bzl", "gos_java_library")

gos_java_library(
    name = "subsystems",
    srcs = glob(["*.java"]),
    visibility = ["//codelabs/pid:__subpackages__"],
    deps = [
        "//GosLib/GirlsOfSteelLib/src/main/java/com/gos/lib/properties",
        "//GosLib/GirlsOfSteelLib/src/main/java/com/gos/lib/properties/pid",
        "//GosLib/GirlsOfSteelLibRev/src/main/java/com/gos/lib/rev/properties/pid",
        "//codelabs/pid/src/main/java/com/gos/codelabs/pid:Constants",
        "//codelabs/pid/src/main/java/com/gos/codelabs/pid:SmartDashboardNames",
        "@bzlmodrio-allwpilib//libraries/java/ntcore",
        "@bzlmodrio-allwpilib//libraries/java/wpilibNewCommands",
        "@bzlmodrio-allwpilib//libraries/java/wpilibj",
        "@bzlmodrio-allwpilib//libraries/java/wpimath",
        "@bzlmodrio-revlib//libraries/java/revlib-java",
        "@maven//:org_snobotv2_snobot_sim_java_base",
        "@maven//:org_snobotv2_snobot_sim_java_revlib",
    ],
)
