rootProject.name = 'GirlsOfSteelRobotics'

//include 'codelabs:basic_simulator'
//include 'codelabs:custom_shuffleboard'
include 'codelabs:gitflow'
//include 'codelabs:pid'
//include 'codelabs:basic_java'
//include 'codelabs:first_robot_code'

include 'GosLib:GirlsOfSteelLib'
include 'GosLib:GirlsOfSteelLibRev'
include 'GosLib:GirlsOfSteelLibPhoenix6'
include 'GosLib:GirlsOfSteelLibPhotonVision'
include 'GosLib:GirlsOfSteelLibPathing'
//include 'libraries:SwerveShuffleboard'

include 'y2026:BunnyBots'
include 'y2026:Rebuilt'

