// RobotBuilder Version: 3.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.subsystems;


import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.drive.MecanumDrive;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Chassis extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Spark m_rightFront;
    private final Spark m_rightBack;
    private final Spark m_leftFront;
    private final Spark m_leftBack;
    private final MecanumDrive m_mecanumDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    /**
     *
     */
    public Chassis() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        m_rightFront = new Spark(1);
        addChild("Right Front", m_rightFront);
        m_rightFront.setInverted(false);

        m_rightBack = new Spark(2);
        addChild("Right Back", m_rightBack);
        m_rightBack.setInverted(false);

        m_leftFront = new Spark(3);
        addChild("Left Front", m_leftFront);
        m_leftFront.setInverted(false);

        m_leftBack = new Spark(4);
        addChild("Left Back", m_leftBack);
        m_leftBack.setInverted(false);

        m_mecanumDrive = new MecanumDrive(m_leftFront, m_leftBack,
                m_rightFront, m_rightBack);
        addChild("Mecanum Drive", m_mecanumDrive);
        m_mecanumDrive.setSafetyEnabled(true);
        m_mecanumDrive.setExpiration(0.1);
        m_mecanumDrive.setMaxOutput(1.0);


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

