// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc.team3504.robot;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Solenoid solenoidTesterSolenoid0;
    public static PowerDistributionPanel powerDistPanelTesterPowerDistPanelInput;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        solenoidTesterSolenoid0 = new Solenoid(0);
        powerDistPanelTesterPowerDistPanelInput = new PowerDistributionPanel();
	LiveWindow.addActuator("SolenoidTester", "Solenoid 0", solenoidTesterSolenoid0);
	// Unfortunately, the PowerDistributionPanel class doesn't implement LiveWindowSendable
	//LiveWindow.addSensor("PowerDistPanelTester", "PowerDistPanelInput", powerDistPanelTesterPowerDistPanelInput);
        
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
