// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3504.OrangeEOPP;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController shooterSpeedController1;
    public static SpeedController driveLeft;
    public static SpeedController driveRight;
    public static SpeedController driveLeft2;
    public static SpeedController driveRight2;
    public static RobotDrive driveRobotDrive;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        shooterSpeedController1 = new Jaguar(6);
//    LiveWindow.addActuator("Shooter", "Speed Controller 1", (Jaguar) shooterSpeedController1);

        driveLeft = new Jaguar(3);
//    addChild("Left", (Jaguar) driveLeft);

        driveRight = new Jaguar(5);
//    addChild("Right", (Jaguar) driveRight);

        driveLeft2 = new Jaguar(4);
//    addChild("Left", (Jaguar) driveLeft2);

        driveRight2 = new Jaguar(1);
//    addChild("Right", (Jaguar) driveRight2);

        driveRobotDrive = new RobotDrive(driveLeft,driveLeft2,driveRight,driveRight2);

        driveRobotDrive.setSafetyEnabled(false);
        driveRobotDrive.setExpiration(0.1);
        driveRobotDrive.setSensitivity(0.5);
        driveRobotDrive.setMaxOutput(1.0);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
