// spotless:off
package frc.robot.choreo_gen;

import java.util.Map;
import java.util.OptionalInt;

import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
// If the 2 imports above cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj OvenToCenterLine = new ChoreoTraj(
        "OvenToCenterLine",
        OptionalInt.empty(),
        2.09746,
        new Pose2d(0.50854, 3.09811, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(7.82769, 1.94214, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj KitchenToOven = new ChoreoTraj(
        "KitchenToOven",
        OptionalInt.empty(),
        1.02549,
        new Pose2d(0.39654, 5.45961, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(0.50854, 3.09811, Rotation2d.fromRadians(-1.5708))
    );
    public static final ChoreoTraj KitchenToPantry = new ChoreoTraj(
        "KitchenToPantry",
        OptionalInt.empty(),
        0.99858,
        new Pose2d(0.39654, 5.45961, Rotation2d.fromRadians(1.5708)),
        new Pose2d(0.96098, 7.63424, Rotation2d.fromRadians(1.5708))
    );
    public static final ChoreoTraj KitchenToRamp = new ChoreoTraj(
        "KitchenToRamp",
        OptionalInt.empty(),
        1.51134,
        new Pose2d(0.39654, 5.45961, Rotation2d.fromRadians(-1.5708)),
        new Pose2d(2.75879, 2.34562, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj KitchenToCenterLine = new ChoreoTraj(
        "KitchenToCenterLine",
        OptionalInt.empty(),
        2.22021,
        new Pose2d(0.39654, 5.45961, Rotation2d.fromRadians(0)),
        new Pose2d(7.82769, 1.94214, Rotation2d.fromRadians(0))
    );
    public static final ChoreoTraj PantryToCenterLine = new ChoreoTraj(
        "PantryToCenterLine",
        OptionalInt.empty(),
        2.37808,
        new Pose2d(0.96098, 7.63424, Rotation2d.fromRadians(1.5708)),
        new Pose2d(7.82769, 1.94214, Rotation2d.fromRadians(0))
    );

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
        Map.entry("OvenToCenterLine", OvenToCenterLine),
        Map.entry("KitchenToOven", KitchenToOven),
        Map.entry("KitchenToPantry", KitchenToPantry),
        Map.entry("KitchenToRamp", KitchenToRamp),
        Map.entry("KitchenToCenterLine", KitchenToCenterLine),
        Map.entry("PantryToCenterLine", PantryToCenterLine)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
// spotless:on
