package com.gos.rebuilt.subsystems;

import static edu.wpi.first.units.Units.Second;
import static edu.wpi.first.units.Units.Volts;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.function.Supplier;

import com.gos.lib.field.AprilTagCameraObject.DebugConfig;

import choreo.util.ChoreoAllianceFlipUtil;
import com.ctre.phoenix6.swerve.SwerveRequest.ForwardPerspectiveValue;
import com.gos.lib.logging.LoggingUtil;


import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.configs.SlotConfigs;
import com.ctre.phoenix6.hardware.CANcoder;
import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;

import com.gos.lib.pathing.MaybeFlippedPose2d;
import com.gos.lib.pathing.MaybeFlippedTranslation3d;
import com.gos.lib.phoenix6.alerts.BasePhoenix6Alerts;
import com.gos.lib.phoenix6.alerts.CancoderAlerts;
import com.gos.lib.phoenix6.alerts.TalonFxAlerts;
import com.gos.lib.phoenix6.properties.pid.Phoenix6TalonPidPropertyBuilder;
import com.gos.lib.phoenix6.properties.pid.PhoenixPidControllerPropertyBuilder;
import com.gos.lib.photonvision.AprilTagCameraBuilder;
import com.gos.lib.photonvision.AprilTagCameraManager;
import com.gos.lib.properties.pid.PidProperty;
import com.gos.lib.swerve.SwerveDrivePublisher;
import com.gos.rebuilt.Constants;
import com.gos.rebuilt.GosField;
import com.gos.rebuilt.RobotExtrinsic;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;

import com.pathplanner.lib.util.PathPlannerLogging;
import edu.wpi.first.apriltag.AprilTagFieldLayout;
import edu.wpi.first.apriltag.AprilTagFields;
import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.Pair;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.geometry.Translation3d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.shuffleboard.Shuffleboard;
import edu.wpi.first.wpilibj.shuffleboard.ShuffleboardTab;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;


import frc.robot.generated.TunerConstants;
import frc.robot.generated.TunerConstants.TunerSwerveDrivetrain;
import org.littletonrobotics.frc2026.FieldConstants.Hub;
import org.photonvision.EstimatedRobotPose;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 * <p>
 * Generated by the 2026 Tuner X Swerve Project Generator
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class ChassisSubsystem extends TunerSwerveDrivetrain implements Subsystem {
    public static final double MAX_TRANSLATION_SPEED = Units.feetToMeters(16);
    public static final double MAX_ROTATION_SPEED = Math.toRadians(540);

    private static final double SIM_LOOP_PERIOD = 0.004; // 4 ms
    private Notifier m_simNotifier;  // NOPMD
    private final PidProperty m_pidControllerProperty;
    private double m_lastSimTime;
    private final LoggingUtil m_networkTableEntries;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d BLUE_ALLIANCE_PERSPECTIVE_ROTATION = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d RED_ALLIANCE_PERSPECTIVE_ROTATION = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective;

    /**
     * Swerve request to apply during robot-centric path following
     */
    private final SwerveRequest.ApplyRobotSpeeds m_pathApplyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    private final List<PidProperty> m_moduleProperties;
    private final List<BasePhoenix6Alerts> m_alerts;

    private static final SlotConfigs DEFAULT_STEER_CONFIG = SlotConfigs.from(TunerConstants.steerGains);
    private static final SlotConfigs DEFAULT_DRIVE_CONFIG = SlotConfigs.from(TunerConstants.driveGains);

    private static final boolean DEBUG_SWERVE_STATE = true;

    private final SwerveDrivePublisher m_swerveDrivePublisher;
    private static final double DEADBAN = Math.toRadians(10);

    private final GosField m_field;
    private final AprilTagCameraManager m_aprilTagCameras;
    private Rotation2d m_goalAngle;

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )


    );


    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(// NOPMD(UnusedPrivateField)
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(// NOPMD(UnusedPrivateField)
        new SysIdRoutine.Config(
            /* This is in radians per second², but SysId only supports "volts per second" */
            Volts.of(Math.PI / 6).per(Second),
            /* This is in radians per second, but SysId only supports "volts" */
            Volts.of(Math.PI),
            null, // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> {
                /* output is actually radians per second, but SysId only supports "volts" */
                setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
                /* also log the requested output for SysId */
                SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
            },
            null,
            this
        )
    );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation; // NOPMD(ImmutableField)


    private final SwerveRequest.FieldCentric m_driveRequest = new SwerveRequest.FieldCentric()
        .withDeadband(MAX_TRANSLATION_SPEED * 0.05)
        .withRotationalDeadband(MAX_ROTATION_SPEED * .05)
        .withDriveRequestType(DriveRequestType.OpenLoopVoltage);

    private final SwerveRequest.FieldCentricFacingAngle m_angleFace = new SwerveRequest.FieldCentricFacingAngle()
        .withDeadband(MAX_TRANSLATION_SPEED * 0.05)
        .withRotationalDeadband(MAX_ROTATION_SPEED * .05)
        .withDriveRequestType(DriveRequestType.OpenLoopVoltage);

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants Drivetrain-wide constants for the swerve drive
     * @param modules             Constants for each specific module
     */
    public ChassisSubsystem(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configureAutoBuilder();

        m_field = new GosField();
        SmartDashboard.putData("Field", m_field.getField2d());
        SmartDashboard.putData("Field3d", m_field.getField3d());

        m_pidControllerProperty = new PhoenixPidControllerPropertyBuilder("chassis Pid", Constants.DEFAULT_CONSTANT_PROPERTIES, m_angleFace.HeadingController)
            .addP(10.0)
            .addD(0.1)
            .build();

        m_alerts = new ArrayList<>();
        m_moduleProperties = new ArrayList<>();
        for (int i = 0; i < 4; ++i) {
            SwerveModule<TalonFX, TalonFX, CANcoder> module = getModule(i);
            m_moduleProperties.add(new Phoenix6TalonPidPropertyBuilder("SdsModule.Steer", Constants.DEFAULT_CONSTANT_PROPERTIES, module.getSteerMotor(), 0)
                .fromDefaults(DEFAULT_STEER_CONFIG)
                .build());
            m_moduleProperties.add(new Phoenix6TalonPidPropertyBuilder("SdsModule.Drive", Constants.DEFAULT_CONSTANT_PROPERTIES, module.getDriveMotor(), 0)
                .fromDefaults(DEFAULT_DRIVE_CONFIG)
                .build());

            m_alerts.add(new TalonFxAlerts(module.getDriveMotor(), "Swerve Drive[" + i + "]"));
            m_alerts.add(new TalonFxAlerts(module.getSteerMotor(), "Swerve Steer[" + i + "]"));
            m_alerts.add(new CancoderAlerts(module.getEncoder()));
        }
        PathPlannerLogging.setLogActivePathCallback(m_field::setTrajectory);
        PathPlannerLogging.setLogTargetPoseCallback(m_field::setTrajectorySetpoint);
        m_swerveDrivePublisher = new SwerveDrivePublisher();



        Matrix<N3, N1> singleTagStddev = VecBuilder.fill(1.5, 1.5, Units.degreesToRadians(180));
        Matrix<N3, N1> multiTagStddev = VecBuilder.fill(.5, 0.5, Units.degreesToRadians(30));


        boolean enableFancyCameraSim = false;

        AprilTagCameraBuilder cameraBuilder = new AprilTagCameraBuilder()
            .withLayout(AprilTagFieldLayout.loadField(AprilTagFields.k2026RebuiltWelded))
            .withField(m_field)
            .withSingleTagStddev(singleTagStddev)
            .withMultiTagStddev(multiTagStddev)
            .withFieldDebugConfig(new DebugConfig(false, true, true))
            .withSingleTagMaxDistanceMeters(4)
            .withSingleTagMaxAmbiguity(.5)
            .withSimEnableRawStream(enableFancyCameraSim)
            .withSimEnableProcessedStream(enableFancyCameraSim)
            .withSimEnableDrawWireframe(enableFancyCameraSim)
            ;


        m_aprilTagCameras = new AprilTagCameraManager(AprilTagFieldLayout.loadField(AprilTagFields.k2026RebuiltWelded), List.of(
            cameraBuilder
                .withCamera("Back Left")
                .withTransform(RobotExtrinsic.BACK_LEFT_CAMERA).build()
        ));



        m_networkTableEntries = new LoggingUtil("Chassis Subsystem");
        m_networkTableEntries.addDouble("Distance", () -> getDistanceToObject(Hub.innerCenterPoint));


        m_networkTableEntries.addBoolean("ichassisgood", this::facingHub);


    }

    private void configureAutoBuilder() {
        try {
            var config = RobotConfig.fromGUISettings();
            AutoBuilder.configure(
                () -> getState().Pose,   // Supplier of current robot pose
                this::resetPose,         // Consumer for seeding pose against auto
                () -> getState().Speeds, // Supplier of current robot speeds
                // Consumer of ChassisSpeeds and feedforwards to drive the robot
                (speeds, feedforwards) -> setControl(
                    m_pathApplyRobotSpeeds.withSpeeds(ChassisSpeeds.discretize(speeds, 0.020))
                        .withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesXNewtons())
                        .withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesYNewtons())
                ),
                new PPHolonomicDriveController(
                    // PID constants for translation
                    new PIDConstants(10, 0, 0),
                    // PID constants for rotation
                    new PIDConstants(7, 0, 0)
                ),
                config,
                // Assume the path needs to be flipped for Red vs Blue, this is normally the case
                () -> DriverStation.getAlliance().orElse(Alliance.Blue) == Alliance.Red,
                this // Subsystem for requirements
            );
        } catch (Exception ex) {  // NOPMD(AvoidCatchingGenericException)
            DriverStation.reportError("Failed to load PathPlanner config and configure AutoBuilder", ex.getStackTrace());
        }
    }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void simulationPeriodic() {
        m_aprilTagCameras.updateSimulator(getState().Pose);
    }


    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? RED_ALLIANCE_PERSPECTIVE_ROTATION
                        : BLUE_ALLIANCE_PERSPECTIVE_ROTATION
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }

        for (PidProperty property : m_moduleProperties) {
            property.updateIfChanged();
        }

        m_field.setPoseEstimate(getState().Pose);
        SwerveDriveState state = getState();

        if (DEBUG_SWERVE_STATE) {
            m_swerveDrivePublisher.setMeasuredStates(state.ModuleStates);
            m_swerveDrivePublisher.setRobotRotation(state.Pose.getRotation());
            m_swerveDrivePublisher.setDesiredStates(state.ModuleTargets);
        }


        List<Pair<EstimatedRobotPose, Matrix<N3, N1>>> estimates = m_aprilTagCameras.update(state.Pose);
        for (Pair<EstimatedRobotPose, Matrix<N3, N1>> estimatePair : estimates) {

            EstimatedRobotPose camPose = estimatePair.getFirst();
            Pose2d camEstPose = camPose.estimatedPose.toPose2d();
            addVisionMeasurement(camEstPose, camPose.timestampSeconds, estimatePair.getSecond());
        }

        m_pidControllerProperty.updateIfChanged();
        m_networkTableEntries.updateLogs();
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(SIM_LOOP_PERIOD);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds      The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters    The pose of the robot as measured by the vision camera.
     * @param timestampSeconds         The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *                                 in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public void driveFieldCentric(double xJoystick, double yJoystick, double rotationalJoystick) {
        setControl(
            m_driveRequest.withVelocityX(xJoystick * MAX_TRANSLATION_SPEED)
                .withVelocityY(yJoystick * MAX_TRANSLATION_SPEED)
                .withRotationalRate(rotationalJoystick * MAX_ROTATION_SPEED)
        );
        m_goalAngle = null; // NOPMD(NullAssignment)
    }

    public void staringDrive(double xJoystick, double yJoystick, Rotation2d goalAngleRad) {
        setControl(
            m_angleFace.withVelocityX(xJoystick * MAX_TRANSLATION_SPEED)
                .withVelocityY(yJoystick * MAX_TRANSLATION_SPEED)
                .withTargetDirection(goalAngleRad)
                .withForwardPerspective(ForwardPerspectiveValue.BlueAlliance)
        );
        m_goalAngle = goalAngleRad;
    }

    public boolean facingHub() {
        if (m_goalAngle == null) {
            return true;
        }
        return Math.abs(m_goalAngle.getRadians() - getState().Pose.getRotation().getRadians()) < DEADBAN;
    }

    public Rotation2d getGoalAngle() {
        return m_goalAngle;
    }

    public Rotation2d getShooterFaceAngle(MaybeFlippedTranslation3d point) {
        return getShooterFaceAngle(point.getTranslation().toTranslation2d());
    }

    public Rotation2d getShooterFaceAngle(Translation2d point) {

        Translation2d shooterPosition = getState().Pose.getTranslation().minus(ShooterSubsystem.SHOOTER_OFFSET.rotateBy(getState().Pose.getRotation()));

        double goalAngle = Math.atan2(shooterPosition.getY() - point.getY(),
            shooterPosition.getX() - point.getX());

        return Rotation2d.fromRadians(goalAngle);
    }

    public double getDistanceToObject(MaybeFlippedTranslation3d point) {
        return getDistanceToObject(point.getTranslation().toTranslation2d());
    }

    public double getDistanceToObject(Translation2d point) {

        Pose2d robotPosition = getState().Pose;
        Pose2d shooterPose = new Pose2d(robotPosition.getTranslation().minus(ShooterSubsystem.SHOOTER_OFFSET.rotateBy(robotPosition.getRotation())), robotPosition.getRotation());
        double distanceX = shooterPose.getX() - point.getX();
        double distanceY = shooterPose.getY() - point.getY();

        return Math.sqrt(distanceX * distanceX + distanceY * distanceY);
    }


    public double getDistanceFromHub() {
        return getDistanceToObject(Hub.innerCenterPoint);
    }

    public void stop() {
        driveFieldCentric(0, 0, 0);
    }

    private void resetPose(MaybeFlippedPose2d maybeFlippedPose) {
        resetPose(maybeFlippedPose.getPose());
    }


    public void addChassisDebugCommands() {
        ShuffleboardTab tab = Shuffleboard.getTab("Chassis");
        tab.add(createFaceHub());
        tab.add(createResetPose(new Pose2d()));

        Translation3d blueHub = Hub.innerCenterPoint.getTranslation();
        Translation3d redHub = ChoreoAllianceFlipUtil.flip(blueHub);
        tab.add(createResetPose(new MaybeFlippedPose2d(blueHub.getX() - 3, blueHub.getY(), Rotation2d.fromDegrees(180))).withName("3m From Blue"));
        tab.add(createResetPose(new MaybeFlippedPose2d(redHub.getX() - 3, redHub.getY(), Rotation2d.fromDegrees(180))).withName("3m From Red"));
    }

    public Command createFaceHub() {
        return runEnd(() -> staringDrive(0, 0, getShooterFaceAngle(Hub.innerCenterPoint)), this::stop).withName("Face Hub");
    }

    public Command createStop() {
        return runOnce(() -> driveFieldCentric(0,0,0));
    }

    public Command createResetPose(MaybeFlippedPose2d pose) {
        return runEnd(() -> resetPose(pose), this::stop).ignoringDisable(true).withName("Reset Robot Pose!!" + pose);
    }

    public Command createResetPose(Pose2d pose) {
        return runEnd(() -> resetPose(pose), this::stop).ignoringDisable(true).withName("Reset Robot Pose!!" + pose);
    }
}
