load("//build_scripts/bazel:java_rules.bzl", "gos_java_robot")

# The subsystems create debug commands, and the commands use the subsystems, so everything
# is built as one target to avoid a circular dependency between the packages.
gos_java_robot(
    name = "basic_simulator",
    srcs = glob(["**/*.java"]),
    disable_pmd = True,
    main_class = "com.gos.codelabs.basic_simulator.Main",
    visibility = ["//codelabs/basic_simulator:__subpackages__"],
    deps = [
        "//GosLib/GirlsOfSteelLib/src/main/java/com/gos/lib/logging",
        "@bzlmodrio-allwpilib//libraries/java/wpilibNewCommands",
        "@bzlmodrio-allwpilib//libraries/java/wpilibj",
        "@bzlmodrio-allwpilib//libraries/java/wpimath",
        "@bzlmodrio-revlib//libraries/java/revlib-java",
        "@maven//:org_snobotv2_snobot_sim_java_base",
        "@maven//:org_snobotv2_snobot_sim_java_revlib",
    ],
)
