
package com.gos.rebuilt.choreo_gen;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj RotatedPath_MaxAccel_01rps = new ChoreoTraj(
	    "RotatedPath_MaxAccel_01rps",
	    OptionalInt.empty(),
	    6.31111,
	    new Pose2d(0, 0, Rotation2d.fromRadians(0)),
	    new Pose2d(6.096, 0, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RotatedPath_MaxAccel_02rps = new ChoreoTraj(
	    "RotatedPath_MaxAccel_02rps",
	    OptionalInt.empty(),
	    3.19437,
	    new Pose2d(0, 0, Rotation2d.fromRadians(0)),
	    new Pose2d(6.096, 0, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RotatedPath_MaxAccel_04rps = new ChoreoTraj(
	    "RotatedPath_MaxAccel_04rps",
	    OptionalInt.empty(),
	    2.11659,
	    new Pose2d(0, 0, Rotation2d.fromRadians(0)),
	    new Pose2d(6.096, 0, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RotatedPath_MaxAccel_08rps = new ChoreoTraj(
	    "RotatedPath_MaxAccel_08rps",
	    OptionalInt.empty(),
	    2.07422,
	    new Pose2d(0, 0, Rotation2d.fromRadians(0)),
	    new Pose2d(6.096, 0, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RotatedPath_MaxAccel_12rps = new ChoreoTraj(
	    "RotatedPath_MaxAccel_12rps",
	    OptionalInt.empty(),
	    3.01396,
	    new Pose2d(0, 0, Rotation2d.fromRadians(0)),
	    new Pose2d(6.096, 0, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RotStrPath_MaxAccel_01rps = new ChoreoTraj(
	    "RotStrPath_MaxAccel_01rps",
	    OptionalInt.empty(),
	    6.31135,
	    new Pose2d(0, 0, Rotation2d.fromRadians(0)),
	    new Pose2d(6.096, 0, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RotStrPath_MaxAccel_05rps = new ChoreoTraj(
	    "RotStrPath_MaxAccel_05rps",
	    OptionalInt.empty(),
	    4.17067,
	    new Pose2d(0, 0, Rotation2d.fromRadians(0)),
	    new Pose2d(6.096, 0, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RotStrPath_MaxAccel_10rps = new ChoreoTraj(
	    "RotStrPath_MaxAccel_10rps",
	    OptionalInt.empty(),
	    2.33954,
	    new Pose2d(0, 0, Rotation2d.fromRadians(0)),
	    new Pose2d(6.096, 0, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj RotStrPath_MaxAccel_15rps = new ChoreoTraj(
	    "RotStrPath_MaxAccel_15rps",
	    OptionalInt.empty(),
	    2.07556,
	    new Pose2d(0, 0, Rotation2d.fromRadians(0)),
	    new Pose2d(6.096, 0, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj StartLeftDepot = new ChoreoTraj(
	    "StartLeftDepot",
	    OptionalInt.empty(),
	    2.27961,
	    new Pose2d(3.564, 7.665, Rotation2d.fromRadians(3.138)),
	    new Pose2d(3.392, 5.417, Rotation2d.fromRadians(2.335))
	);
	public static final ChoreoTraj StartLeftDepot$0 = new ChoreoTraj(
	    "StartLeftDepot",
	    OptionalInt.of(0),
	    1.20259,
	    new Pose2d(3.564, 7.665, Rotation2d.fromRadians(3.138)),
	    new Pose2d(0.858, 5.945, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj StartLeftDepot$1 = new ChoreoTraj(
	    "StartLeftDepot",
	    OptionalInt.of(1),
	    1.0770199999999999,
	    new Pose2d(0.858, 5.945, Rotation2d.fromRadians(3.142)),
	    new Pose2d(3.392, 5.417, Rotation2d.fromRadians(2.335))
	);
	public static final ChoreoTraj StartLeftPreload = new ChoreoTraj(
	    "StartLeftPreload",
	    OptionalInt.empty(),
	    0.96461,
	    new Pose2d(3.564, 7.665, Rotation2d.fromRadians(3.138)),
	    new Pose2d(3.222, 5.606, Rotation2d.fromRadians(2.691))
	);
	public static final ChoreoTraj StartMiddleShootMiddle = new ChoreoTraj(
	    "StartMiddleShootMiddle",
	    OptionalInt.empty(),
	    0.70022,
	    new Pose2d(3.584, 3.981, Rotation2d.fromRadians(3.142)),
	    new Pose2d(2.479, 3.996, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj StartRightOutpost = new ChoreoTraj(
	    "StartRightOutpost",
	    OptionalInt.empty(),
	    2.45922,
	    new Pose2d(3.584, 0.392, Rotation2d.fromRadians(3.142)),
	    new Pose2d(3.375, 2.476, Rotation2d.fromRadians(-2.251))
	);
	public static final ChoreoTraj StartRightOutpost$0 = new ChoreoTraj(
	    "StartRightOutpost",
	    OptionalInt.of(0),
	    1.19735,
	    new Pose2d(3.584, 0.392, Rotation2d.fromRadians(3.142)),
	    new Pose2d(0.419, 0.675, Rotation2d.fromRadians(-3.142))
	);
	public static final ChoreoTraj StartRightOutpost$1 = new ChoreoTraj(
	    "StartRightOutpost",
	    OptionalInt.of(1),
	    1.2618700000000003,
	    new Pose2d(0.419, 0.675, Rotation2d.fromRadians(-3.142)),
	    new Pose2d(3.375, 2.476, Rotation2d.fromRadians(-2.251))
	);
	public static final ChoreoTraj StartRightPreload = new ChoreoTraj(
	    "StartRightPreload",
	    OptionalInt.empty(),
	    0.96104,
	    new Pose2d(3.584, 0.392, Rotation2d.fromRadians(3.142)),
	    new Pose2d(3.066, 2.391, Rotation2d.fromRadians(-2.412))
	);
	public static final ChoreoTraj StraightPathNAV_MaxAccel_01fps = new ChoreoTraj(
	    "StraightPathNAV_MaxAccel_01fps",
	    OptionalInt.empty(),
	    20.05072,
	    new Pose2d(0, 0, Rotation2d.fromRadians(0)),
	    new Pose2d(6.096, 0, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj StraightPathNAV_MaxAccel_05fps = new ChoreoTraj(
	    "StraightPathNAV_MaxAccel_05fps",
	    OptionalInt.empty(),
	    4.17153,
	    new Pose2d(0, 0, Rotation2d.fromRadians(0)),
	    new Pose2d(6.096, 0, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj StraightPathNAV_MaxAccel_10fps = new ChoreoTraj(
	    "StraightPathNAV_MaxAccel_10fps",
	    OptionalInt.empty(),
	    2.33954,
	    new Pose2d(0, 0, Rotation2d.fromRadians(0)),
	    new Pose2d(6.096, 0, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj StraightPathNAV_MaxAccel_15fps = new ChoreoTraj(
	    "StraightPathNAV_MaxAccel_15fps",
	    OptionalInt.empty(),
	    2.07418,
	    new Pose2d(0, 0, Rotation2d.fromRadians(0)),
	    new Pose2d(6.096, 0, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj StraightPath_MaxAccel_01fps = new ChoreoTraj(
	    "StraightPath_MaxAccel_01fps",
	    OptionalInt.empty(),
	    20.054,
	    new Pose2d(0, 0, Rotation2d.fromRadians(0)),
	    new Pose2d(6.096, 0, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj StraightPath_MaxAccel_05fps = new ChoreoTraj(
	    "StraightPath_MaxAccel_05fps",
	    OptionalInt.empty(),
	    4.17334,
	    new Pose2d(0, 0, Rotation2d.fromRadians(0)),
	    new Pose2d(6.096, 0, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj StraightPath_MaxAccel_10fps = new ChoreoTraj(
	    "StraightPath_MaxAccel_10fps",
	    OptionalInt.empty(),
	    2.33971,
	    new Pose2d(0, 0, Rotation2d.fromRadians(0)),
	    new Pose2d(6.096, 0, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj StraightPath_MaxAccel_MaxSpeed = new ChoreoTraj(
	    "StraightPath_MaxAccel_MaxSpeed",
	    OptionalInt.empty(),
	    1.81238,
	    new Pose2d(0, 0, Rotation2d.fromRadians(0)),
	    new Pose2d(6.096, 0, Rotation2d.fromRadians(0))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("RotatedPath_MaxAccel_01rps", RotatedPath_MaxAccel_01rps),
		Map.entry("RotatedPath_MaxAccel_02rps", RotatedPath_MaxAccel_02rps),
		Map.entry("RotatedPath_MaxAccel_04rps", RotatedPath_MaxAccel_04rps),
		Map.entry("RotatedPath_MaxAccel_08rps", RotatedPath_MaxAccel_08rps),
		Map.entry("RotatedPath_MaxAccel_12rps", RotatedPath_MaxAccel_12rps),
		Map.entry("RotStrPath_MaxAccel_01rps", RotStrPath_MaxAccel_01rps),
		Map.entry("RotStrPath_MaxAccel_05rps", RotStrPath_MaxAccel_05rps),
		Map.entry("RotStrPath_MaxAccel_10rps", RotStrPath_MaxAccel_10rps),
		Map.entry("RotStrPath_MaxAccel_15rps", RotStrPath_MaxAccel_15rps),
		Map.entry("StartLeftDepot", StartLeftDepot),
		Map.entry("StartLeftDepot$0", StartLeftDepot$0),
		Map.entry("StartLeftDepot$1", StartLeftDepot$1),
		Map.entry("StartLeftPreload", StartLeftPreload),
		Map.entry("StartMiddleShootMiddle", StartMiddleShootMiddle),
		Map.entry("StartRightOutpost", StartRightOutpost),
		Map.entry("StartRightOutpost$0", StartRightOutpost$0),
		Map.entry("StartRightOutpost$1", StartRightOutpost$1),
		Map.entry("StartRightPreload", StartRightPreload),
		Map.entry("StraightPathNAV_MaxAccel_01fps", StraightPathNAV_MaxAccel_01fps),
		Map.entry("StraightPathNAV_MaxAccel_05fps", StraightPathNAV_MaxAccel_05fps),
		Map.entry("StraightPathNAV_MaxAccel_10fps", StraightPathNAV_MaxAccel_10fps),
		Map.entry("StraightPathNAV_MaxAccel_15fps", StraightPathNAV_MaxAccel_15fps),
		Map.entry("StraightPath_MaxAccel_01fps", StraightPath_MaxAccel_01fps),
		Map.entry("StraightPath_MaxAccel_05fps", StraightPath_MaxAccel_05fps),
		Map.entry("StraightPath_MaxAccel_10fps", StraightPath_MaxAccel_10fps),
		Map.entry("StraightPath_MaxAccel_MaxSpeed", StraightPath_MaxAccel_MaxSpeed)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
