# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

resources:
  containers:
  - container: wpilib2019
    image: wpilib/roborio-cross-ubuntu:2019-18.04
  - container: ubuntu18
    image: ubuntu:18.04
    options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"

stages:
- stage: Build
  jobs:

   - job: Linux
     pool:
       vmImage: 'Ubuntu 16.04'

     container: wpilib2019

     steps:
     - task: Gradle@2
       inputs:
         workingDirectory:  '2019DeepSpace'
         gradleWrapperFile: '2019DeepSpace/gradlew'
         gradleOptions: '-Xmx3072m'
         publishJUnitResults: true
         testResultsFiles: '**/TEST-*.xml'
         tasks: 'build'

   - job: Windows_64_Bit
     pool:
       vmImage: 'vs2017-win2016'
     steps:
      - powershell: |
          mkdir build
          $ProgressPreference = 'SilentlyContinue'
          wget "https://download.java.net/java/ga/jdk11/openjdk-11_windows-x64_bin.zip" -O "build\jdk.zip"
        displayName: 'Download JDK'
      - task: JavaToolInstaller@0
        inputs:
          jdkSourceOption: localDirectory
          jdkFile: 'build/jdk.zip'
          jdkDestinationDirectory: 'build/jdkinst'
          jdkArchitectureOption: x64
      - task: Gradle@2
        inputs:
          workingDirectory:  '2019DeepSpace'
          gradleWrapperFile: '2019DeepSpace/gradlew'
          gradleOptions: '-Xmx3072m'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'build'


   - job: Windows_32_Bit
     pool:
       vmImage: 'vs2017-win2016'
     steps:
      - powershell: |
          mkdir build
          $ProgressPreference = 'SilentlyContinue'
          wget "https://github.com/wpilibsuite/frc-openjdk-windows/releases/download/v11.0.0u28-1/jdk-x86-11.0.0u28-1.zip" -O "build\jdk.zip"
        displayName: 'Download JDK'
      - task: JavaToolInstaller@0
        inputs:
          jdkSourceOption: localDirectory
          jdkFile: 'build/jdk.zip'
          jdkDestinationDirectory: 'build/jdkinst'
          jdkArchitectureOption: x86
      - task: Gradle@2
        inputs:
          workingDirectory:  '2019DeepSpace'
          gradleWrapperFile: '2019DeepSpace/gradlew'
          gradleOptions: '-Xmx1024m'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'build'

   - job: Mac
     pool:
       vmImage: 'xcode9-macos10.13'
     steps:
      - script: |
          mkdir build
          wget "https://download.java.net/java/ga/jdk11/openjdk-11_osx-x64_bin.tar.gz" -O "build/jdk.tar.gz"
          sudo tar xvzf build/jdk.tar.gz -C /Library/Java/JavaVirtualMachines/
          export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home/
        displayName: 'Setup JDK'
      - task: Gradle@2
        inputs:
          workingDirectory:  '2019DeepSpace'
          gradleWrapperFile: '2019DeepSpace/gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'path'
          jdkDirectory: '/Library/Java/JavaVirtualMachines/jdk-11.jdk/Contents/Home/'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'build'
