// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc3504.OrangeEOPP.commands;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3504.OrangeEOPP.Robot;
/**
 *
 */
public class  DrivebyJoystick extends Command {

    Joystick joy;

    public DrivebyJoystick() {
        //get joystick
        requires(Robot.drive);
        //joy = Robot.oi.getJoystick();
    }
    // Called just before this Command runs the first time
    protected void initialize() {
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        //move in direction of joystick
       // double x = joy.getX();
       // double y = joy.getY();

        Robot.drive.move(Robot.oi.getJoystick());
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }
    // Called once after isFinished returns true
    protected void end() {
        //Stop the motors when we end driving
        Robot.drive.stop();
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
