// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc3504.ShifterBotNew;

import org.usfirst.frc3504.ShifterBotNew.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.buttons.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);
    
    // Another type of button you can create is a DigitalIOButton, which is
    // a button or switch hooked up to the cypress module. These are useful if
    // you want to build a customized operator interface.
    // Button button = new DigitalIOButton(1);
    
    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.
    
    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:
    
    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());
    
    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());
    
    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());

    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton joystickButton2;
    public JoystickButton joystickButton3;
    public JoystickButton joystickButton5;
    public JoystickButton joystickButton6;
    public JoystickButton joystickButton10;
    public JoystickButton joystickButton11;
    public Joystick driveStick;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        driveStick = new Joystick(1);
        
        joystickButton11 = new JoystickButton(driveStick, 11);
        joystickButton11.whileHeld(new AccessoryRightRev());
        joystickButton10 = new JoystickButton(driveStick, 10);
        joystickButton10.whileHeld(new AccessoryRightFwd());
        joystickButton6 = new JoystickButton(driveStick, 6);
        joystickButton6.whileHeld(new AccessoryLeftRev());
        joystickButton5 = new JoystickButton(driveStick, 5);
        joystickButton5.whileHeld(new AccessoryLeftFwd());
        joystickButton3 = new JoystickButton(driveStick, 3);
        joystickButton3.whenPressed(new ShiftUp());
        joystickButton2 = new JoystickButton(driveStick, 2);
        joystickButton2.whenPressed(new ShiftDown());

	    
        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous Command", new AutonomousCommand());

        SmartDashboard.putData("DriveByJoystick", new DriveByJoystick());

        SmartDashboard.putData("Shift Up", new ShiftUp());

        SmartDashboard.putData("Shift Down", new ShiftDown());

        SmartDashboard.putData("Accessory Left Fwd", new AccessoryLeftFwd());

        SmartDashboard.putData("Accessory Left Rev", new AccessoryLeftRev());

        SmartDashboard.putData("Accessory Right Fwd", new AccessoryRightFwd());

        SmartDashboard.putData("Accessory Right Rev", new AccessoryRightRev());

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getDriveStick() {
        return driveStick;
    }

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

