// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


package org.usfirst.frc3504.ShifterBotNew;
    
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveSystemDriveLeft;
    public static SpeedController driveSystemDriveRight;
    public static RobotDrive driveSystemRobotDrive2;
    public static SpeedController accessoryMotorsAccessoryLeft;
    public static SpeedController accessoryMotorsAccessoryRight;
    public static DoubleSolenoid shiftersShifterLeft;
    public static DoubleSolenoid shiftersShifterRight;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveSystemDriveLeft = new Talon(0);
	LiveWindow.addActuator("Drive System", "Drive Left", (Talon) driveSystemDriveLeft);
        
        driveSystemDriveRight = new Talon(1);
	LiveWindow.addActuator("Drive System", "Drive Right", (Talon) driveSystemDriveRight);
        
        driveSystemRobotDrive2 = new RobotDrive(driveSystemDriveLeft, driveSystemDriveRight);
	
        driveSystemRobotDrive2.setSafetyEnabled(true);
        driveSystemRobotDrive2.setExpiration(0.1);
        driveSystemRobotDrive2.setSensitivity(0.5);
        driveSystemRobotDrive2.setMaxOutput(1.0);
        

        accessoryMotorsAccessoryLeft = new Talon(2);
	LiveWindow.addActuator("Accessory Motors", "Accessory Left", (Talon) accessoryMotorsAccessoryLeft);
        
        accessoryMotorsAccessoryRight = new Talon(3);
	LiveWindow.addActuator("Accessory Motors", "Accessory Right", (Talon) accessoryMotorsAccessoryRight);
        
        shiftersShifterLeft = new DoubleSolenoid(0, 0, 1);      
	
        
        shiftersShifterRight = new DoubleSolenoid(0, 2, 3);      
	
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
