name: Lint

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:

  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          version: "23.1.0"

  lint_versions:
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run Linter
        run: python libraries/linters/gradlerio_versions/lint_gradlerio_versions.py

      - name: Generate diff
        run: git diff HEAD > lint-version-fixes.patch
        if: ${{ failure() }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-lint-version-fixes
          path: lint-version-fixes.patch
        if: ${{ failure() }}
