name: Update Checker

on: [workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup git
        run: |
          git config --global user.email "girlsofsteelrobotics@gmail.com"
          git config --global user.name "Girls of Steel Robotics"

      - name: Fetch
        run: git fetch origin dnl_enable_all_projects_and_spotless

      - name: Check for updates
        run: python3 -m libraries.scripts.updater.update_everything

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_UPDATE_KEY }}
        with:
          base: main
          title: Update Robot Libraries
          branch: update_robot_deps
          token: ${{ secrets.AUTO_UPDATE_KEY }}

